{
 "title": "Whammyflex_miner_stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hash_attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "wfx_hash_attempts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total_mint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "wfx_total_minted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Valid_Shares",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "wfx_hash_attempts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU_Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wfx_cpu_core_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Miner Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wfx_miner_up", "legendFormat": "__auto" }
   ]
  }
 ]
}